using System.Collections.Concurrent;
using System.Diagnostics;
using AxarDB.Definitions;

namespace AxarDB.Bridges
{
    /// <summary>
    /// Singleton in-memory store with TTL (Time-To-Live) support.
    /// Collections are stored in memory only; data is not persisted to disk.
    /// Expired entries are cleaned up lazily on access and periodically via a background timer.
    /// </summary>
    public class MemoryStore
    {
        private readonly ConcurrentDictionary<string, ConcurrentDictionary<string, MemoryEntry>> _collections = new();
        private readonly Timer _cleanupTimer;

        // Per-collection active (non-expired) record count. Maintained on insert/delete so
        // GetRecordCount is O(1) instead of scanning the whole collection every call — this is
        // the core reason an in-memory store must stay faster than a disk-backed (bulk) store.
        private readonly ConcurrentDictionary<string, long> _activeCounts = new();

        // Cached, non-expired document list per collection. FindAll returns this reference
        // directly (no per-call copy), mirroring BulkStore's GetDocuments. The cache is kept in
        // sync on insert/delete/cleanup; a dirty flag forces a lazy rebuild only when needed
        // (TTL expiry). The common path therefore stays allocation-free and O(1).
        private readonly object _cacheLock = new();
        private readonly Dictionary<string, List<Dictionary<string, object>>> _cache = new();
        private readonly HashSet<string> _cacheDirty = new();

        // Diagnostic logging toggle (set AXARDB_DIAG=1 to enable verbose per-step timing).
        private static readonly bool Diag = Environment.GetEnvironmentVariable("AXARDB_DIAG") == "1";
        private static void Log(string step, string detail, long ms, long count = -1)
        {
            if (!Diag) return;
            var c = count >= 0 ? $" count={count}" : "";
            Console.WriteLine($"[diag:memory] {step}{c} | {detail} | {ms} ms");
            Console.Out.Flush();
        }

        public MemoryStore()
        {
            // Cleanup expired entries every 5 minutes
            _cleanupTimer = new Timer(_ => CleanupExpired(), null, TimeSpan.FromMinutes(5), TimeSpan.FromMinutes(5));
        }

        public struct MemoryEntry
        {
            public Dictionary<string, object> Document { get; set; }
            public DateTime ExpiresAt { get; set; }

            public bool IsExpired => ServerTime.Now > ExpiresAt;
        }

        public IEnumerable<string> GetCollectionNames() => _collections.Keys;

        public int GetRecordCount(string name)
        {
            var sw = Stopwatch.StartNew();
            long count = _activeCounts.TryGetValue(name, out var c) ? c : 0;
            sw.Stop();
            Log("GetRecordCount", name, sw.ElapsedMilliseconds, count);
            return (int)count;
        }

        private ConcurrentDictionary<string, MemoryEntry> GetOrCreateCollection(string name)
        {
            return _collections.GetOrAdd(name, _ => new ConcurrentDictionary<string, MemoryEntry>());
        }

        /// <summary>
        /// Insert a document into the named collection with a TTL in hours (default: 1 hour).
        /// Any caller-supplied _id is silently removed; the engine always generates a fresh one.
        /// </summary>
        public Dictionary<string, object> Insert(string collectionName, Dictionary<string, object> document, double hours = 1.0)
        {
            // _id is always generated by the engine — silently remove any caller-supplied value
            document.Remove("_id");
            document["_id"] = AxarDB.Helpers.GuidV7.NewGuid().ToString();

            var id = document["_id"].ToString()!;
            var col = GetOrCreateCollection(collectionName);

            var entry = new MemoryEntry
            {
                Document = document,
                ExpiresAt = ServerTime.Now.AddHours(hours)
            };

            col[id] = entry;
            _activeCounts.AddOrUpdate(collectionName, 1, (_, c) => c + 1);

            if (entry.ExpiresAt > ServerTime.Now)
                AddToCache(collectionName, document);
            else
                MarkDirty(collectionName);

            Log("Insert(single)", collectionName, 0, 1);
            return document;
        }

        /// <summary>
        /// Inserts a batch of documents in a single call (used for bulk loading).
        /// Returns the number of documents inserted.
        /// </summary>
        public int Insert(string collectionName, IEnumerable<Dictionary<string, object>> documents, double hours = 1.0)
        {
            var sw = Stopwatch.StartNew();
            var col = GetOrCreateCollection(collectionName);
            int count = 0;
            var now = ServerTime.Now;
            var added = new List<Dictionary<string, object>>();
            bool hasExpired = false;
            foreach (var document in documents)
            {
                // _id is always generated by the engine — silently remove any caller-supplied value
                document.Remove("_id");
                document["_id"] = AxarDB.Helpers.GuidV7.NewGuid().ToString();

                var id = document["_id"].ToString()!;
                var entry = new MemoryEntry
                {
                    Document = document,
                    ExpiresAt = now.AddHours(hours)
                };

                col[id] = entry;
                count++;
                if (entry.ExpiresAt > now)
                    added.Add(document);
                else
                    hasExpired = true;
            }
            _activeCounts.AddOrUpdate(collectionName, count, (_, c) => c + count);

            if (added.Count > 0)
                AddRangeToCache(collectionName, added);
            if (hasExpired)
                MarkDirty(collectionName);

            sw.Stop();
            Log("Insert(batch)", $"{collectionName} docs={count}", sw.ElapsedMilliseconds, count);
            return count;
        }

        /// <summary>
        /// Returns all non-expired documents from the named collection.
        /// The result is the cached document list returned by reference — no per-call copy —
        /// so repeated findall() calls stay cheap and the in-memory store outpaces disk reads.
        /// A lazy rebuild happens only when the cache is marked dirty (TTL expiry).
        /// </summary>
        public IEnumerable<Dictionary<string, object>> FindAll(string collectionName)
        {
            var sw = Stopwatch.StartNew();
            if (!_collections.TryGetValue(collectionName, out var col))
            {
                sw.Stop();
                Log("FindAll", $"{collectionName} (missing)", sw.ElapsedMilliseconds, 0);
                return Enumerable.Empty<Dictionary<string, object>>();
            }

            List<Dictionary<string, object>> cached;
            lock (_cacheLock)
            {
                if (_cacheDirty.Contains(collectionName) || !_cache.TryGetValue(collectionName, out cached!))
                {
                    var now = ServerTime.Now;
                    cached = col.Values
                        .Where(v => v.ExpiresAt > now)
                        .Select(v => v.Document)
                        .ToList();
                    _cache[collectionName] = cached;
                    _cacheDirty.Remove(collectionName);
                }
            }
            sw.Stop();
            Log("FindAll", collectionName, sw.ElapsedMilliseconds, cached.Count);
            return cached;
        }

        /// <summary>
        /// Deletes documents matching the predicate from the named collection.
        /// </summary>
        public void Delete(string collectionName, Func<Dictionary<string, object>, bool> predicate)
        {
            var sw = Stopwatch.StartNew();
            if (!_collections.TryGetValue(collectionName, out var col)) return;

            var toDelete = col
                .Where(kvp => !kvp.Value.IsExpired && predicate(kvp.Value.Document))
                .Select(kvp => kvp.Key)
                .ToList();

            foreach (var key in toDelete)
                col.TryRemove(key, out _);

            if (toDelete.Count > 0)
            {
                _activeCounts.AddOrUpdate(collectionName, 0, (_, c) => Math.Max(0, c - toDelete.Count));
                lock (_cacheLock)
                {
                    if (_cache.TryGetValue(collectionName, out var list))
                        list.RemoveAll(d => predicate(d));
                }
            }

            sw.Stop();
            Log("Delete", $"{collectionName} removed={toDelete.Count}", sw.ElapsedMilliseconds, toDelete.Count);
        }

        public void Update(string collectionName, string id, Dictionary<string, object> document)
        {
            if (!_collections.TryGetValue(collectionName, out var col)) return;
            if (col.TryGetValue(id, out var entry))
            {
                entry.Document = document;
                col[id] = entry; // Update struct
            }
        }

        /// <summary>
        /// Completely removes a collection and all its documents from the store.
        /// After this call the collection will no longer appear in GetCollectionNames().
        /// </summary>
        public void DropCollection(string collectionName)
        {
            _collections.TryRemove(collectionName, out _);
            _activeCounts.TryRemove(collectionName, out _);
            lock (_cacheLock)
            {
                _cache.Remove(collectionName);
                _cacheDirty.Remove(collectionName);
            }
        }

        /// <summary>
        /// Removes all expired entries across all collections.
        /// </summary>
        private void CleanupExpired()
        {
            foreach (var kvp in _collections)
            {
                var col = kvp.Value;
                var expired = col.Where(kvp2 => kvp2.Value.IsExpired).Select(kvp2 => kvp2.Key).ToList();
                foreach (var key in expired)
                    col.TryRemove(key, out _);
                if (expired.Count > 0)
                {
                    _activeCounts.AddOrUpdate(kvp.Key, 0, (_, c) => Math.Max(0, c - expired.Count));
                    MarkDirty(kvp.Key);
                }
            }
        }

        private void AddToCache(string collectionName, Dictionary<string, object> document)
        {
            lock (_cacheLock)
            {
                if (!_cache.TryGetValue(collectionName, out var list))
                {
                    list = new List<Dictionary<string, object>>();
                    _cache[collectionName] = list;
                }
                list.Add(document);
            }
        }

        private void AddRangeToCache(string collectionName, List<Dictionary<string, object>> documents)
        {
            lock (_cacheLock)
            {
                if (!_cache.TryGetValue(collectionName, out var list))
                {
                    list = new List<Dictionary<string, object>>();
                    _cache[collectionName] = list;
                }
                list.AddRange(documents);
            }
        }

        private void MarkDirty(string collectionName)
        {
            lock (_cacheLock)
                _cacheDirty.Add(collectionName);
        }
    }
}
