using System.Collections.Concurrent;
using AxarDB.Storage;
using Microsoft.Extensions.Caching.Memory;

namespace AxarDB.Definitions
{
    public class Collection
    {
        public string Name { get; private set; }
        public List<IndexDefinition> Indices { get; set; } = new();
        private readonly DiskStorage _storage;
        
        // Hybrid Caching - Shared
        private readonly IMemoryCache _cache;
        private readonly HashSet<string> _primaryIndex = new();
        private readonly object _indexLock = new object();
        private int _indexSaveCounter = 0;
        private const int IndexSaveDebounceInterval = 100;

        public Collection(string name, DiskStorage storage, IMemoryCache sharedCache)
        {
            Name = name;
            _storage = storage;
            // NOTE: EnsureCollection is NOT called here intentionally.
            // The collection directory is created lazily on the first write (Insert).
            // This prevents empty directories from being created for collections
            // that are only read (e.g. db.nonExistent.findall()).
            _cache = sharedCache;
            
        // 1. Load Primary Index (IDs only) - FAST
            Reload();
        }

        public void Reload()
        {            
            lock (_indexLock)
            {
                _primaryIndex.Clear();
                foreach (var id in _storage.GetAllDocumentIds(Name))
                {
                    _primaryIndex.Add(id);
                }
            }
            
            // Indices
            Indices.Clear();
            var path = Path.Combine(_storage.BasePath, Name);
            if (Directory.Exists(path))
            {
                foreach (var file in Directory.EnumerateFiles(path, "idx_*.json"))
                {
                    var idx = IndexDefinition.Load(file);
                    if (idx != null) Indices.Add(idx);
                }
            }
        }

        private string GetCacheKey(string id) => $"{Name}:{id}";

        private Dictionary<string, object>? GetDocument(string id)
        {
            var key = GetCacheKey(id);
            Dictionary<string, object>? doc = null;

            // Cache Look-aside
            if (_cache.TryGetValue<Dictionary<string, object>>(key, out var cachedDoc))
            {
                 doc = cachedDoc;
            }
            else
            {
                // Disk Read
                doc = _storage.LoadDocument(Name, id);
                
                if (doc != null)
                {
                    // Accurate Bytes estimate (UTF-16 string length * 2)
                    long size = System.Text.Json.JsonSerializer.Serialize(doc).Length * 2L; 
                    if (size < 1000) size = 1000; // minimum size threshold
                    
                    var entryOptions = new MemoryCacheEntryOptions
                    {
                        Size = size,
                        SlidingExpiration = TimeSpan.FromMinutes(10) 
                    };
                    
                    _cache.Set(key, doc, entryOptions);
                }
            }
            
            // CRITICAL: Return DeepCopy to prevent in-memory mutation by Safe Queries
            if (doc != null)
            {
                // We use ScriptUtils.DeepCopy which uses our new JSON converter
                var copy = AxarDB.Helpers.ScriptUtils.DeepCopy(doc) as Dictionary<string, object>;
                return copy;
            }
            return null;
        }

        public void Insert(Dictionary<string, object> document, CancellationToken cancellationToken = default, bool bypassSystemRules = false)
        {
            if (Name.StartsWith("sys", StringComparison.OrdinalIgnoreCase))
            {
                if (!Name.Equals("sysusers", StringComparison.OrdinalIgnoreCase) &&
                    !Name.Equals("sysqueue", StringComparison.OrdinalIgnoreCase) &&
                    !Name.Equals("sysvaults", StringComparison.OrdinalIgnoreCase) &&
                    !Name.Equals("sysconfig", StringComparison.OrdinalIgnoreCase) &&
                    !Name.Equals("syslogs", StringComparison.OrdinalIgnoreCase))
                {
                    throw new InvalidOperationException("Users cannot create custom system collections starting with 'sys'.");
                }

                if ((Name.Equals("sysconfig", StringComparison.OrdinalIgnoreCase) || Name.Equals("syslogs", StringComparison.OrdinalIgnoreCase)) && !bypassSystemRules)
                {
                    throw new InvalidOperationException($"Insert operation is not allowed on {Name} collection.");
                }
            }

            // _id is always generated by the engine — silently remove any caller-supplied value
            document.Remove("_id");

            if (Name.Equals("sysvaults", StringComparison.OrdinalIgnoreCase))
            {
                if (document.TryGetValue("key", out var keyObj) && keyObj != null)
                {
                    string keyStr = keyObj.ToString()!;
                    var existing = FindAll(cancellationToken).FirstOrDefault(d => 
                        d.TryGetValue("key", out var existingKeyObj) && 
                        existingKeyObj != null && 
                        existingKeyObj.ToString() == keyStr);

                    if (existing != null)
                    {
                        string existingId = existing["_id"].ToString()!;
                        document["_id"] = existingId;

                        if (!document.ContainsKey("created") || document["created"] == null)
                        {
                            if (existing.TryGetValue("created", out var existingCreated))
                            {
                                document["created"] = existingCreated;
                            }
                        }

                        UpdateExisting(document, existing, cancellationToken, bypassSystemRules);
                        return;
                    }
                }
            }

            document["_id"] = AxarDB.Helpers.GuidV7.NewGuid().ToString();
            string id = document["_id"].ToString()!;
            
            // Validate system collection structure
            ValidateSystemCollectionStructure(document);

            // Ensure the collection directory exists on first write (lazy creation)
            _storage.EnsureCollection(Name);

            // --- Backup Query: Insert ---
            try
            {
                var query = $"db.{Name}.findall(x => x._id == '{id}').delete()";
                AxarDB.Core.BackupQuery.LogRecoveryQuery(Directory.GetParent(_storage.BasePath)!.FullName, query);
            }
            catch (Exception ex)
            {
                AxarDB.Logging.Logger.LogError($"[BackupQuery Error] Failed to create backup query for insert: {ex.Message}");
            }
            // -----------------------------

            // 1. Disk Persist
            _storage.SaveDocument(Name, document);

            // 2. Update Index
            lock (_indexLock) { _primaryIndex.Add(id); }

            // 3. Update/Invalidate Cache
            long size = System.Text.Json.JsonSerializer.Serialize(document).Length * 2L;
            if (size < 1000) size = 1000;
            
            var entryOptions = new MemoryCacheEntryOptions
            {
                Size = size,
                SlidingExpiration = TimeSpan.FromMinutes(10)
            };
            _cache.Set(GetCacheKey(id), document, entryOptions);

            // 4. Update Secondary Indexes
            foreach (var index in Indices)
            {
                cancellationToken.ThrowIfCancellationRequested();
                index.IndexDocument(document);
            }

            // Debounced index persistence — save every N inserts
            if (++_indexSaveCounter >= IndexSaveDebounceInterval)
            {
                SaveIndices();
            }
        }

        public IEnumerable<Dictionary<string, object>> FindAll(CancellationToken cancellationToken = default)
        {
            string[] ids;
            lock (_indexLock) { ids = _primaryIndex.ToArray(); }
            
            return ids.AsParallel().WithCancellation(cancellationToken)
                      .Select(id => GetDocument(id))
                      .Where(doc => doc != null)!;
        }

        public IEnumerable<Dictionary<string, object>> FindAll(Func<Dictionary<string, object>, bool> predicate, AxarDB.Query.QueryOptimizer.AnalysisResult? analysis = null, CancellationToken cancellationToken = default)
        {
             // Optimization: If analyzed and index available, use it
             if (analysis != null && analysis.Value.Prop != null)
             {
                 var idx = Indices.FirstOrDefault(i => i.PropertyName == analysis.Value.Prop);
                 if (idx != null)
                 {
                     var ids = idx.Search(analysis.Value.Val!, analysis.Value.Op);

                     // Index results are already a small set; return lazily so downstream
                     // Take(N) can short-circuit without materializing the full list.
                     return ids.AsParallel()
                               .WithCancellation(cancellationToken)
                               .WithMergeOptions(ParallelMergeOptions.NotBuffered)
                               .Select(id => GetDocument(id))
                               .Where(doc => doc != null)
                               .Select(doc => doc!);
                 }

                 // Full scan — C# optimized evaluator (no Jint, no engine lock needed).
                 // NotBuffered lets downstream Take(N) stop the parallel pipeline early.
                 string[] allIds2;
                 lock (_indexLock) { allIds2 = _primaryIndex.ToArray(); }

                 return allIds2.AsParallel()
                               .WithCancellation(cancellationToken)
                               .WithMergeOptions(ParallelMergeOptions.NotBuffered)
                               .Select(id => GetDocument(id))
                               .Where(doc => doc != null)
                               .Select(doc => doc!)
                               .Where(doc => AxarDB.Query.QueryOptimizer.Evaluate(doc, analysis.Value));
             }

             // Full scan — Jint JS evaluator (slow path).
             // lock(_engine) in the predicate lambda already serializes evaluation across
             // threads, so AsParallel() was adding thread-pool overhead with zero benefit.
             // A sequential lazy LINQ chain lets Take(N) terminate after N matches.
             string[] allIds;
             lock (_indexLock) { allIds = _primaryIndex.ToArray(); }

             return allIds
                    .TakeWhile(_ => !cancellationToken.IsCancellationRequested)
                    .Select(id => GetDocument(id))
                    .Where(doc => doc != null)
                    .Select(doc => doc!)
                    .Where(predicate);
        }

        public void CreateIndex(string propertyName, string type)
        {
            var index = new IndexDefinition(propertyName, type);
            // Re-index existing data
            // Use local FindAll to leverage parallel load
            foreach (var doc in FindAll())
            {
                index.IndexDocument(doc);
            }
            Indices.Add(index);
            _storage.EnsureCollection(Name);
            index.Save(Path.Combine(_storage.BasePath, Name));
        }

        public void SaveIndices()
        {
            _indexSaveCounter = 0;
            _storage.EnsureCollection(Name);
            var path = Path.Combine(_storage.BasePath, Name);
            foreach (var index in Indices)
            {
                index.Save(path);
            }
        }

        public void UpdateExisting(Dictionary<string, object> document, Dictionary<string, object> oldDocument, CancellationToken cancellationToken = default, bool bypassSystemRules = false)
        {
            if (!document.TryGetValue("_id", out var idObj) || idObj == null)
            {
                throw new ArgumentException("Document must contain an '_id' field for updates.");
            }

            string id = idObj.ToString()!;

            lock (_indexLock)
            {
                if (!_primaryIndex.Contains(id))
                {
                    throw new KeyNotFoundException($"Document with ID '{id}' was not found in primary index to update.");
                }
            }

            if (Name.StartsWith("sys", StringComparison.OrdinalIgnoreCase))
            {
                if (!Name.Equals("sysusers", StringComparison.OrdinalIgnoreCase) &&
                    !Name.Equals("sysqueue", StringComparison.OrdinalIgnoreCase) &&
                    !Name.Equals("sysvaults", StringComparison.OrdinalIgnoreCase) &&
                    !Name.Equals("sysconfig", StringComparison.OrdinalIgnoreCase) &&
                    !Name.Equals("syslogs", StringComparison.OrdinalIgnoreCase))
                {
                    throw new InvalidOperationException("Users cannot modify custom system collections starting with 'sys'.");
                }

                if ((Name.Equals("sysconfig", StringComparison.OrdinalIgnoreCase) || Name.Equals("syslogs", StringComparison.OrdinalIgnoreCase)) && !bypassSystemRules)
                {
                    throw new InvalidOperationException($"Update operation is not allowed on {Name} collection.");
                }
            }

            ValidateSystemCollectionStructure(document);

            // --- Backup Query: Update ---
            try
            {
                var json = System.Text.Json.JsonSerializer.Serialize(oldDocument);
                var query = $"db.{Name}.update(x => x._id == '{id}', {json})";
                AxarDB.Core.BackupQuery.LogRecoveryQuery(Directory.GetParent(_storage.BasePath)!.FullName, query);
            }
            catch (Exception ex)
            {
                AxarDB.Logging.Logger.LogError($"[BackupQuery Error] Failed to create backup query for update: {ex.Message}");
            }
            // -----------------------------

            // 1. Disk Persist
            _storage.SaveDocument(Name, document);

            // 2. Update/Invalidate Cache
            long size = System.Text.Json.JsonSerializer.Serialize(document).Length * 2L;
            if (size < 1000) size = 1000;
            
            var entryOptions = new MemoryCacheEntryOptions
            {
                Size = size,
                SlidingExpiration = TimeSpan.FromMinutes(10)
            };
            _cache.Set(GetCacheKey(id), document, entryOptions);

            // 3. Update Secondary Indexes
            foreach (var index in Indices)
            {
                cancellationToken.ThrowIfCancellationRequested();
                if (oldDocument.TryGetValue(index.PropertyName, out var oldPropVal))
                {
                    index.RemoveDocument(id, oldPropVal);
                }
                index.IndexDocument(document);
            }

            // Debounced index persistence
            if (++_indexSaveCounter >= IndexSaveDebounceInterval)
            {
                SaveIndices();
            }
        }

        public void Update(Func<Dictionary<string, object>, bool> predicate, Dictionary<string, object> updateFields, CancellationToken cancellationToken = default)
        {
            // 1. Identify matches (Parallel Scan) -- pass token!
            var matches = FindAll(predicate, null, cancellationToken).ToList();
            
            if (matches.Count == 0)
            {
                throw new KeyNotFoundException("No documents matched the update predicate.");
            }
            
            // 2. Perform Updates
            foreach (var doc in matches)
            {
                 cancellationToken.ThrowIfCancellationRequested();
                 
                 // Deep copy old document for index cleanup
                 var oldDocCopy = AxarDB.Helpers.ScriptUtils.DeepCopy(doc) as Dictionary<string, object>;
                 string id = doc["_id"].ToString()!;

                 foreach (var kvp in updateFields)
                 {
                     if (kvp.Key == "_id") continue; // Prevent altering _id
                     doc[kvp.Key] = kvp.Value;
                 }
                 doc["_id"] = id; // Enforce original _id

                 UpdateExisting(doc, oldDocCopy!, cancellationToken, bypassSystemRules: true);
            }
            SaveIndices();
        }

        public void Delete(Func<Dictionary<string, object>, bool> predicate, CancellationToken cancellationToken = default)
        {
            var matches = FindAll(predicate, null, cancellationToken);
            
            foreach (var doc in matches)
            {
                cancellationToken.ThrowIfCancellationRequested();
                if (doc.TryGetValue("_id", out var idObj))
                {
                    string id = idObj.ToString()!;

                    // --- Backup Query: Delete ---
                    try
                    {
                        var json = System.Text.Json.JsonSerializer.Serialize(doc);
                        var query = $"db.{Name}.insert({json})";
                        AxarDB.Core.BackupQuery.LogRecoveryQuery(Directory.GetParent(_storage.BasePath)!.FullName, query);
                    }
                    catch (Exception ex)
                    {
                        AxarDB.Logging.Logger.LogError($"[BackupQuery Error] Failed to create backup query for delete: {ex.Message}");
                    }
                    // -----------------------------

                    // Update Disk
                    _storage.DeleteDocument(Name, id);
                    // Update Primary Index
                    lock (_indexLock) { _primaryIndex.Remove(id); }
                    // Update Secondary Indices
                    foreach (var index in Indices)
                    {
                        if (doc.TryGetValue(index.PropertyName, out var propVal))
                            index.RemoveDocument(id, propVal);
                    }
                    // Update Cache
                    _cache.Remove(GetCacheKey(id));
                }
            }
            SaveIndices();
        }
        public void OnExternalChange(string id, string evtType)
        {
            // Handle external file changes (manual edit, FTP, etc.)
            // We need to reflect these changes in Memory (Index & Cache)
            
            if (evtType == "deleted")
            {
                lock (_indexLock) { _primaryIndex.Remove(id); }
                _cache.Remove(GetCacheKey(id));
                // Try to load the document to clean up secondary indices
                var deletedDoc = _storage.LoadDocument(Name, id);
                if (deletedDoc != null)
                {
                    foreach (var index in Indices)
                    {
                        if (deletedDoc.TryGetValue(index.PropertyName, out var propVal))
                            index.RemoveDocument(id, propVal);
                    }
                }
                SaveIndices();
            }
            else if (evtType == "created")
            {
                lock (_indexLock) { _primaryIndex.Add(id); }
                var doc = _storage.LoadDocument(Name, id);
                if (doc != null)
                {
                    foreach (var index in Indices) index.IndexDocument(doc);
                }
                SaveIndices();
            }
            else if (evtType == "changed")
            {
                _cache.Remove(GetCacheKey(id));
                
                var doc = _storage.LoadDocument(Name, id);
                if (doc != null)
                {
                    foreach (var index in Indices) index.IndexDocument(doc);
                }
                SaveIndices();
            }
        }

        // --- System Collection Validation Infrastructure ---
        private static readonly Dictionary<string, HashSet<string>> SystemCollectionSchemas = new(StringComparer.OrdinalIgnoreCase)
        {
            { "sysusers", new HashSet<string> { "_id", "username", "password" } },
            { "sysvaults", new HashSet<string> { "_id", "key", "value", "created" } },
            { "sysconfig", new HashSet<string> { "_id", "memoryLimitPercentage", "bulkStoreMaxCacheBytes", "maxRecursionDepth", "queryTimeoutMinutes", "queuePollIntervalSeconds", "timezoneOffset" } },
            { "sysqueue", new HashSet<string> { "_id", "queryTemplate", "parameters", "options", "createdAt", "executionTime", "priority", "duration", "successResult", "errorMessage", "completedAt" } },
            { "syslogs", new HashSet<string> { "_id", "timestamp", "type", "ip", "user", "query", "durationMs", "status" } }
        };

        private static readonly Dictionary<string, Dictionary<string, Type>> SystemCollectionTypes = new(StringComparer.OrdinalIgnoreCase)
        {
            {
                "sysusers", new Dictionary<string, Type>
                {
                    { "_id", typeof(string) },
                    { "username", typeof(string) },
                    { "password", typeof(string) }
                }
            },
            {
                "sysvaults", new Dictionary<string, Type>
                {
                    { "_id", typeof(string) },
                    { "key", typeof(string) },
                    { "created", typeof(DateTime) }
                }
            },
            {
                "sysconfig", new Dictionary<string, Type>
                {
                    { "_id", typeof(string) },
                    { "memoryLimitPercentage", typeof(double) },
                    { "bulkStoreMaxCacheBytes", typeof(long) },
                    { "maxRecursionDepth", typeof(int) },
                    { "queryTimeoutMinutes", typeof(int) },
                    { "queuePollIntervalSeconds", typeof(double) },
                    { "timezoneOffset", typeof(double) }
                }
            },
            {
                "sysqueue", new Dictionary<string, Type>
                {
                    { "_id", typeof(string) },
                    { "queryTemplate", typeof(string) },
                    { "createdAt", typeof(DateTime) },
                    { "priority", typeof(int) },
                    { "duration", typeof(long) },
                    { "completedAt", typeof(DateTime) }
                }
            }
        };

        private static readonly HashSet<string> FlexibleFields = new(StringComparer.OrdinalIgnoreCase)
        {
            "value", "parameters", "options", "successResult"
        };

        private void ValidateSystemCollectionStructure(Dictionary<string, object> document)
        {
            if (!Name.StartsWith("sys")) return;

            HashSet<string>? expectedKeys = null;
            Dictionary<string, Type>? expectedTypes = null;

            if (SystemCollectionSchemas.TryGetValue(Name, out var predefinedKeys))
            {
                expectedKeys = predefinedKeys;
                SystemCollectionTypes.TryGetValue(Name, out expectedTypes);

                // Add any missing expected keys to ensure backward compatibility and successful validation
                foreach (var expectedKey in expectedKeys)
                {
                    if (!document.ContainsKey(expectedKey))
                    {
                        document[expectedKey] = null!;
                    }
                }
            }
            else
            {
                // Fallback to dynamic schema from first document
                var firstDoc = FindAll().FirstOrDefault();
                if (firstDoc != null)
                {
                    expectedKeys = new HashSet<string>(firstDoc.Keys);
                    expectedTypes = firstDoc.ToDictionary(kvp => kvp.Key, kvp => kvp.Value?.GetType() ?? typeof(object));
                }
            }

            if (expectedKeys != null)
            {
                // Check if keys match exactly (no fields added, no fields removed)
                if (document.Count != expectedKeys.Count || !document.Keys.All(expectedKeys.Contains))
                {
                    var docKeysStr = string.Join(", ", document.Keys);
                    var expKeysStr = string.Join(", ", expectedKeys);
                    throw new InvalidOperationException($"Document structure does not conform to the system collection '{Name}' schema. Expected keys: [{expKeysStr}], got: [{docKeysStr}]. Count expected: {expectedKeys.Count}, got: {document.Count}");
                }

                // Check type compatibility
                if (expectedTypes != null)
                {
                    foreach (var kvp in expectedTypes)
                    {
                        var key = kvp.Key;
                        var expectedType = kvp.Value;

                        if (expectedType != typeof(object) && !FlexibleFields.Contains(key))
                        {
                            if (document.TryGetValue(key, out var docVal) && docVal != null)
                            {
                                var docType = docVal.GetType();
                                if (!AreTypesCompatible(expectedType, docType))
                                {
                                    throw new InvalidOperationException($"Type mismatch for field '{key}' in system collection '{Name}'. Expected compatible with {expectedType.Name}, got {docType.Name}.");
                                }
                            }
                        }
                    }
                }
            }
        }

        private static bool AreTypesCompatible(Type expectedType, Type actualType)
        {
            if (expectedType == actualType) return true;

            // Allow string and DateTime compatibility (dates can be stored/passed as strings)
            if ((expectedType == typeof(DateTime) && actualType == typeof(string)) ||
                (expectedType == typeof(string) && actualType == typeof(DateTime)))
            {
                return true;
            }

            // Check if both are numeric
            if (IsNumericType(expectedType) && IsNumericType(actualType)) return true;

            // Check if both are dictionary/object types
            if (typeof(System.Collections.IDictionary).IsAssignableFrom(expectedType) && 
                typeof(System.Collections.IDictionary).IsAssignableFrom(actualType))
            {
                return true;
            }

            return false;
        }

        private static bool IsNumericType(Type type)
        {
            switch (Type.GetTypeCode(type))
            {
                case TypeCode.Byte:
                case TypeCode.SByte:
                case TypeCode.UInt16:
                case TypeCode.UInt32:
                case TypeCode.UInt64:
                case TypeCode.Int16:
                case TypeCode.Int32:
                case TypeCode.Int64:
                case TypeCode.Decimal:
                case TypeCode.Double:
                case TypeCode.Single:
                    return true;
                default:
                    return false;
            }
        }
    }
}
